---
title: "`r proposal`"
subtitle: ISC proposal
author: "`r author`"
date: "`r Sys.Date()`"
output: html_document
bibliography: ["proposal/FAIReLABS-ics-proposal.bib", "proposal/packages.bib"]
---

```{r setup, eval=TRUE, results='hide', echo=FALSE}
knitr::opts_knit$set(warning = FALSE, message= FALSE, echo= FALSE)
```

```{r pkgs, eval=FALSE, echo= FALSE}
# run for bibtex of pkgs
pkgs <- c("readr", "vroom", "xrftools", "isoreader", "point", "cpp11", 
          "devtools", "pkgdown", "tibble") 
rirods <- bibentry(
  key = "rirods",
  bibtype = "Misc",
  title = "The rirods package enables access to file objects in the iRODS data broker system from R",
  author =  c("Radovan Chytracek", "Bernhard Sonderegger", "Richard Cote", "Russell Terrell"),
  year = "2015",
  url = "https://github.com/irods/irods_client_library_r_cpp/blob/master/DESCRIPTION"
  )
knitr::write_bib(pkgs, "proposal/packages.bib", prefix = "") 
pkgs <- bibtex::read.bib("proposal/packages.bib")
bibtex::write.bib(
  purrr::reduce(list(rirods, pkgs), append), 
  file = "proposal/packages.bib"
  )
```

```{r autodoc, child='proposal/signatories.Rmd', eval=TRUE}
```

```{r autodoc, child='proposal/problemdefinition.Rmd', eval=TRUE}
```

```{r autodoc, child='proposal/proposal.Rmd', eval=TRUE}
```

```{r autodoc, child='proposal/timeline.Rmd', eval=TRUE}
```

```{r autodoc, child='proposal/requirements.Rmd', eval=TRUE}
```

```{r autodoc, child='proposal/success.Rmd', eval=TRUE}
```

# References